### ISSUE TITLE
sriov net support

### ISSUE THREAD

**Issue by dparalen** [RedHatQE/dva#42]
the sriov net support should be a default flag when registering an HVM ami (when RHEL6.7 is out)
Please, verify&close the [bug 1094996](https://bugzilla.redhat.com/show_bug.cgi?id=1094996) and [bug 1103921] (https://bugzilla.redhat.com/show_bug.cgi?id=1103921) once it is out; see also [testcase_63_sriov] (https://github.com/RedHatQE/dva/blob/master/dva/test/testcase_63_sriov.py).

**Comment by Skullman** [comment]
It's out and verified.
