### ISSUE TITLE
dva terminate doesn't reduce the iteration count if it was successful terminating an instance

### ISSUE THREAD

**Issue by dparalen** [RedHatQE/dva#46]
successful instance termination needn't follow by retrying to terminate the same instance in other regions

**Comment by alexxa** [comment]
But I was told like in a different region there can be an instance with the same id?

**Comment by dparalen** [comment]
Yeah, sorry, it was me who told you that. Actually I'm afraid it  reveals another issue: suppose there are indeed 2 instances in different regions that have the same ID. Furthermore, suppose one of the instances is indeed a validation one and should be terminated while the second one is e.g. your WordPress instance. Now the `terminate` function can't distinguish which one to keep and which one to terminate.
I know either way of looping through the termination candidates won't make it any better. We can just hope this won't happen too often.
Not sure what to do, but the reducing approach should be twice faster on average while still being incorrect :)

**Comment by alexxa** [comment]
I see your point. I will take some time to think about all variants and the solution.

**Comment by alexxa** [comment]
@dparalen, all problems come from the thing that we parse broken yaml file, so we can't be sure that one given ami id match its real region - they are written in separate strings/variables. There is no string in output validation file which contains a pair id + region, isn't there? Is it possible to create a variable during validation process which contains id+region and write it to the output file? Then we can strip the broken yaml file for such pairs and feed it to terminate function.

**Comment by dparalen** [comment]
That might work indeed; just make it a custom easy-to-match single-line value in each validation result record.

**Comment by alexxa** [comment]
This issue is not applicable, since another termination model was implemented. See https://github.com/RedHatQE/dva/pull/49
