### ISSUE TITLE
dva terminate to gracefully catch and report EC2 errors

### ISSUE THREAD

**Issue by Skullman** [RedHatQE/dva#50]
For example if you try to terminate instance that has api termination forbidden, you will get operation not permitted xml:

Exception EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>OperationNotPermitted</Code><Message>The instance 'i-fed7dabc' may not be terminated. Modify its 'disableApiTermination' instance attribute and try again.</Message></Error></Errors><RequestID>0cb5104d</RequestID></Response>

**Comment by alexxa** [comment]
Fixed by commit d4d8506
